apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-world-service

spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      # Within cluster
      port: 8080
      # Port to forward to inside pod / container
      targetPort: 80
      # Outside Cluster (valid range is 30000-32767)
      nodePort: 30003
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world

spec:
  selector:
    matchLabels:
      app: hello-world

  # Number of desired pods
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          ports:
           - containerPort: 80
