apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: demo-app-service

spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      # External (Outside Cluster)
      # User http://EXTERNAL-IP:7999/demo/app with GCP
      # NOTE: minikube not handling this well, use nodePort with `minikube ip`
      port: 7999
      # app in container
      targetPort: 8080
      #  Cluster Traffic : let kubernetes select that port
      # nodePort: 30003
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app

spec:
  selector:
    matchLabels:
      app: demo-app

  # Number of desired pods
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: sfogo/demo-app
          ports:
           - containerPort: 8080
