apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: demo-app-service

spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      # Within cluster
      port: 8080
      # Port to forward to inside pod / container
      targetPort: 8080
      # Outside Cluster (valid range is 30000-32767)
      nodePort: 30003
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app

spec:
  selector:
    matchLabels:
      app: demo-app

  # Number of desired pods
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: sfogo/demo-app
          ports:
           - containerPort: 8080
